baseURL = 'https://r-tatsu.github.io/'
title = 'Ryo Tazma Webpage'
theme = "hello-friend-ng"
hasCJKLanguage = true
publishDir = "docs"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages.en]
  languageCode = "en"
  languageName = "English"
  weight = 1

  [[languages.en.menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    weight = 1

  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 2

[languages.ja]
  languageCode = "ja"
  languageName = "日本語"
  weight = 2

  [[languages.ja.menu.main]]
    identifier = "blog"
    name = "技術ブログ"
    url = "/posts"
    weight = 1

  [[languages.ja.menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 2

[params]
  author = "r-tatsu"
  homeSubtitle = "RTL | Exploring AI & Machine Learning"

  [params.logo]
    logoText = "r-tatsu"

  [[params.social]]
    name = "github"
    url = "https://github.com/r-tatsu"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/r-tatsu"

  [[params.social]]
    name = "email"
    url = "mailto:ryota.tatsuuma.pa@hitachi.com"

  [[params.social]]
    name = "orcid"
    url = "https://orcid.org/0009-0001-6199-1261"

  [params.footer]
    trademark = '2025 Ryo Tazma - powered by Hugo'
