baseURL = 'https://r-tatsu.github.io/'
title = 'Ryo Tazma Webpage'
languageCode = 'ja'
theme = "hello-friend-ng"

hasCJKLanguage = true
publishDir = "docs"

[params]

  author = "r-tatsu"
  dateform        = "Feb, 2025"
  dateformShort   = "Feb 25"
  dateformNum     = "2025-02-25"
  dateformNumTime = "2025-02-25 00:00 +0900"

  # homeSubtitle = "this website is currenty being updated."
  homeSubtitle = "RTL | Exploring AI & Machine Learning"

  [params.logo]
  # logoText = "RTL | Exploring AI & Machine Learning"
    logoText = "r-tatsu"

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.

  [[params.social]]
    name = "github"
    url = "https://github.com/r-tatsu"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/r-tatsu"
